### PR TITLE
properly close files and add gitignore entry for pycharm stuff

### PR DESCRIPTION
**Pull request by pascal-de-ladurantaye**

### CODE REVIEW

**Comment by pascal-de-ladurantaye** [comment]
@cr0hn here you go! Please tell me when you push a new version to Pypi with this fix please :)

**Comment by pascal-de-ladurantaye** [comment]
fixes #24

**Comment by pascal-de-ladurantaye** [comment]
Also, if you ever need help maintaining this project, I'm open since we user that library at my workplace

**Comment by pascal-de-ladurantaye** [comment]
@cr0hn any thoughts?

**Comment by cr0hn** [comment]
@pascal-de-ladurantaye it will be great. I'll add as a commiter to this repo.

**Pull request merged**
